### ISSUE TITLE
Lack of passive skill information.

### ISSUE THREAD

**Issue by alachhman** [PokemonMastersDB/apiserver#1]
On [pokemon api response](https://pokemonsmastersdb.herokuapp.com/api/pokemon) there are no value fields pertaining to the passive skills a pokemon has.

**Comment by juanlatorre** [comment]
@alachhman I'm sorry but currently I hace zero time to push changes and updates to this api, if someone wants to take care of it, I will be very happy.

**Comment by alachhman** [comment]
Would you mind if I did so? I'm the main developer for the r/pokemonmasters discord bot.

**Comment by juanlatorre** [comment]
@alachhman oh I would be pleased! I will add you to the organization asap, thank you so much!

**Comment by alachhman** [comment]
@juanlatorre much appreciated, I look forward to contributing.
